import '@/styles/globals.css'
import Head from 'next/head'
import Layout from "@/components/layout"


export default function App({ Component, pageProps }) {
  return (
    <>
       <Head>
       <title>FRAME STUDIO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
       </Head>
        <Layout>
        <Component {...pageProps} />
        </Layout>
    </>
  )
}
